language: java
script: mvn clean deploy -DskipTests --settings travis-settings.xml
jdk:
- oraclejdk7
env:
  global:
    - SONATYPE_USERNAME=luzx02
    - secure: MCiJ3+fsUoHxs0/y1pqY3e6uyfKCscwEqBZso7JIDxDT08EHuag9TDAJ6sSTGqUsex5pYGVazhd7/93bnJEcb1RObJ0Eg+musECdCjMKhCvhu0matGO6MkefqfvtzbR91Mbs1c7/7qMw7sPErSRnlKgLDjZbBnU1GMEBoEXltYwwqeafz1WUkmUD4PjtGaVqHbbi1+zvP0vPUvmbOz9JG5xz8mIa3RTc/9BSuIwd6hbvnqpmb434I5mDKYFFeB/hODwZrkFZ4bWjzfims5LaK7y9z6OPwbdpcVcqqZ7rSwS1nmwCQ8/bTz1w9cpNcDp714UZL+5JtXcTmbORafBvThlLoKew6OOq2KAwgnLTQstN9kL/5Eu81j0naRkJCnLPUsqCcBHyyAiK5hygQ5iqSCgLdjlA1xjs8XoDwckQQOZe02S2KNDyD4PwkmGsuBQowPrfyJfU6hfzTzPprd2wHpkB01Zq5tLFuozKFdnrUI9VlRIP3YWD/KvGoSLdXpdOa/KwMxkGetr9oJ0PzbfzzSzLhwbOYKTrPASvesAmOamuTGQKGIFHvddMuAYhOVB/C2UEV7Uv0hJbnGY6NuIIdq5SO3vZwdmcDlW1VZHXAHq1rVxizMqsZu0MkYsr1vzKXDZ/Xn5YsaFUAMGglDY6zC540az3cJsfSKsl2J/y6Lo=

# safelist
branches:
  only:
    - master
    - develop
#after_success:
#   - python addServer.py
#   - mvn clean deploy -DskipTests --settings travis-settings.xml
